apiVersion: v1
kind: Pod
metadata:
  name: vault-kubernetes
spec:
  serviceAccountName: vault-auth
  containers:
  - name: vault-kubernetes
    image: arungupta/vault-kubernetes:latest
    env:
      - name: VAULT_ADDR
        valueFrom:
          configMapKeyRef:
            name: vault
            key: address
  restartPolicy: Never
