apiVersion: v1
kind: Pod
metadata:
  name: aws-cli
  labels:
    name: aws-cli
spec:
  containers:
    - image: cgswong/aws:aws
      command:
        - "sleep"
        - "9999999"
      name: aws-cli