apiVersion: v1
kind: Service
metadata:
  name: flaskxray-service
spec:
  selector:
    app: flaskxray-pod
  ports:
  - name: http
    protocol: TCP
    port: 80
    targetPort: 5000
  type: LoadBalancer