apiVersion: v1
kind: Service
metadata:
  name: name-service
spec:
  selector:
    app: name-pod
  ports:
    - port: 8080
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: name-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: name-pod
  template:
    metadata:
      labels:
        app: name-pod
    spec:
      containers:
      - name: name
        image: <CHANGEME:NAMEIMAGE>
        env:
        - name: AWS_XRAY_DAEMON_ADDRESS
          value: 172.17.0.1:2000
        - name: AWS_XRAY_CONTEXT_MISSING
          value: LOG_ERROR
        ports:
        - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: greeter-service
spec:
  selector:
    app: greeter-pod
  ports:
    - port: 8080
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: greeter-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: greeter-pod
  template:
    metadata:
      labels:
        app: greeter-pod
    spec:
      containers:
      - name: greeter
        image: <CHANGEME:GREETIMAGE>
        env:
        - name: AWS_XRAY_DAEMON_ADDRESS
          value: 172.17.0.1:2000
        - name: AWS_XRAY_CONTEXT_MISSING
          value: LOG_ERROR
        ports:
        - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: webapp-service
spec:
  selector:
    app: webapp-pod
  ports:
    - name: web
      port: 80
      targetPort: 8080
  type: LoadBalancer
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: webapp-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: webapp-pod
  template:
    metadata:
      labels:
        app: webapp-pod
    spec:
      containers:
      - name: webapp-pod
        image: <CHANGEME:WEBAPPIMAGE>
        env:
        - name: AWS_XRAY_DAEMON_ADDRESS
          value: 172.17.0.1:2000
        - name: AWS_XRAY_CONTEXT_MISSING
          value: LOG_ERROR
        - name: NAME_SERVICE_HOST
          value: name-service
        - name: NAME_SERVICE_PORT
          value: "8080"
        - name: NAME_SERVICE_PATH
          value: /
        - name: GREETER_SERVICE_HOST
          value: greeter-service
        - name: GREETER_SERVICE_PORT
          value: "8080"
        - name: GREETER_SERVICE_PATH
          value: /
        ports:
        - containerPort: 8080
